config/routes.rb
Rails.application.routes.draw do

  root to: redirect("/top")

  get 'history/new'

  #MENU001
  get 'top' => 'menu#menu001'

  scope '/main' do
    #JBOH001
    get 'history' => 'history#index'
    get 'history/:id' => 'history#show'
    #JBOM002 ~ JBOM005
    get 'jobm/new' => 'jobm#new'
    get 'jobm/show' => 'jobm#show'
    post 'jobm' => 'jobm#create'
    delete 'jobm/:id' => 'jobm#destroy'
    get 'jobm/:id/execute' => 'jobm#execute', as: 'jobm_execute'

    #JBOM101 ~ JBOM104
    get 'jobm1/new' => 'jobm1#new'
    get 'jobm1/show' => 'jobm1#show'
    post 'jobm1' => 'jobm1#create'
    post 'jobm1/confirm' => 'jobm1#confirm'
    get 'jobm1/finish' => 'jobm1#finish'
    delete 'jobm1/:id' => 'jobm1#destroy'
  end

  #JOBM001
  #JOBD001
  resources :main, only: [:index, :show] do
    #JOBA001
    get 'jobcommand', to: 'main#jobcommand'
    #JOBR001
    get 'jobr/new' => 'jobr#new'
    #JOBR002
    post 'jobr/confirm' => 'jobr#confirm'
    #JOBR003
    post 'jobr' => 'jobr#create'
    #JOBR004
    get 'jobr/show' => 'jobr#show'
    delete 'jobr/:id' => 'jobr#destroy'

    #JOBD101
    get 'jobd/new' => 'jobd#new'
    #JOBDD102
    post 'jobd/confirm' => 'jobd#confirm'
    #JOBD0103
    post 'jobd' => 'jobd#create'
    #JOBD104
    get 'jobd/finish' => 'jobd#finish'
    get 'jobd/show' => 'jobd#show'
    delete 'jobd/:id' => 'jobd#destroy'
  end

  #MENU002
  get 'menu/menu002'

  scope 'setting' do
    #CONF001
    get 'conf' => 'conf#index'
    #CONF002,CONF003
    get 'conf/:id' => 'conf#show'
    post 'conf/:id' => 'conf#update', as: 'conf_update'
    get 'conf/:id/done' => 'conf#done', as: 'conf_done'

    #CONF101
    get 'conf1' => 'conf1#index'
    get 'conf1/new' => 'conf1#new'
    post 'conf1/new' => 'conf1#create'
    get 'conf1/:id' => 'conf1#show'
    post 'conf1/:id' => 'conf1#update'
    post 'conf1' => 'conf1#update'
    delete 'conf1/:id' => 'conf1#destroy'

    #CONF201
    get 'conf2' => 'conf2#index'
    post 'conf2' => 'conf2#update'
    post 'conf2/search' => 'conf2#search'
    get 'conf2/search' => 'conf2#search'
    post 'conf2/new' => 'conf2#new'
    delete 'conf2' => 'conf2#destroy'
    get 'download' => 'conf2#download'

    #CONF202
    get 'viewlog' => 'conf2#history'
    get 'downloadlog' => 'conf2#downloadlog'
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController

#	helper_method :map_priority
#	helper_method :map_type_cd

  JOBTYPE_MONTH = 0
  JOBTYPE_ACCESS = 1

  NAVAIL_TASK_SUMMARY = -1

  #JOBM001
  def index
    @job_acces = Job.where(type_cd: JOBTYPE_ACCESS).order({ created_at: :desc }, :created_at).includes(:task_summaries, :job_status)
    @acces_progress_list = {}
    @acces_navail_list = {}
    @job_acces.each do |f|
      #進捗率
      progress = ActiveRecord::Base.connection.select_value("SELECT get_job_prograte('#{f.job_id}')")
      @acces_progress_list["#{f.job_id}"] = progress
      #自粛リスト
      navail = f.task_summaries.detect { |j| j.carrier_type_cd == NAVAIL_TASK_SUMMARY }
      if navail.blank? || navail.ok_recs.blank?
        @acces_navail_list["#{f.job_id}"] = 0
      else
        @acces_navail_list["#{f.job_id}"] = navail.ok_recs
      end
    end
    @month_progress_list = {}
    @month_navail_list = {}
    @job_month = Job.where(type_cd: JOBTYPE_MONTH).order({ created_at: :desc }, :created_at).includes(:task_summaries, :job_status)
    @job_month.each do |f|
      #進捗率
      progress = ActiveRecord::Base.connection.select_value("SELECT get_job_prograte('#{f.job_id}')")
      @month_progress_list["#{f.job_id}"] = progress
      #自粛リスト
      navail = f.task_summaries.detect { |j| j.carrier_type_cd == NAVAIL_TASK_SUMMARY }
      if navail.blank? || navail.ok_recs.blank? 
        @month_navail_list["#{f.job_id}"] = 0
      else
        @month_navail_list["#{f.job_id}"] = navail.ok_recs
      end
    end
    #回線エラー
    @errors = TaskSummary.where.not("carrier_type_cd = -1").group(:job_id).sum(:err_recs)

    #自粛エラー
    @navail_errors = TaskSummary.where("carrier_type_cd = -1").group(:job_id).sum(:err_recs)

    #自粛リスト
    @navail_ok = TaskSummary.where("carrier_type_cd = -1").group(:job_id).sum(:ok_recs)

  end

  #JOBD001
  def show
    @job = Job.find_by(job_id: params[:id])
		#削除された or 不正なjob_idの場合、indexへリダイレクト
		if @job.nil?
			redirect_to main_index_path and return
		end
    @file = TelnumFile.order(created_at: :desc).find_by(job_id: @job.job_id)
    @progress = ActiveRecord::Base.connection.select_value("SELECT get_job_prograte('#{@job.job_id}')")
    @navail = TaskSummary.find_by(job_id: @job.job_id, carrier_type_cd: -1)
    #残り件数
    @left = @job.alltask_recs
    @job.task_summaries.each do |f|
      if f.ok_recs.nil? 
        @left = (@job.alltask_recs - 0) if f.carrier_type_cd != -1
      else
        @left -= f.ok_recs if f.carrier_type_cd != -1
        @left -= f.err_recs if f.carrier_type_cd != -1
      end
    end
    @left -= @navail.ok_recs if @navail.nil? == false && @navail.ok_recs.nil? == false 
    logger.debug(@left)
    #調査開始時刻
    #経過時間
    if (@job.started_at.blank?)
      @startdatetime = ""
      @elapsed = ""
    else
      @startdatetime = @job.started_at.to_s(:datetime)
			if @job.job_status.status_cd == 3 || @job.job_status.status_cd == 4
				elapsed_sec = @job.finished_at - @job.started_at
			else
	      elapsed_sec = (Time.new - @job.started_at)
			end
      elapsed_day = (elapsed_sec / (60 * 60 * 24)).floor
      elapsed_sec -= elapsed_day * 60 * 60 * 24
      elapsed_hour = (elapsed_sec / (60 * 60)).floor
      elapsed_sec -= elapsed_hour * 60 * 60
      elapsed_min = (elapsed_sec / 60).floor
      @elapsed = "#{elapsed_day}日 #{elapsed_hour}時間 #{elapsed_min}分"
    end
    #完了予定
    if @job.job_status.status_cd == 1 || @job.job_status.status_cd == 2
    	@estimated = ActiveRecord::Base.connection.select_value("SELECT get_job_expdt('#{@job.job_id}')")
			date_ary = @estimated.split(" ")
			year = date_ary[0]
			year = year.gsub!(/-/, '/')
			time = date_ary[1]
			time = time.split(".")
			time = time[0]
			@estimated = year + " " + time
		elsif @job.job_status.status_cd == 3 || @job.job_status.status_cd == 4
			if !@job.finished_at.blank?
				@estimated = @job.finished_at.to_s(:datetime)
			else
				@estimated = ""
			end
		else
			@estimated = ""
		end

    #キャリア種別
    @carriers = {}
    TaskSummary.where(job_id: @job.job_id).each do |f|
      if f.carrier_type_cd == -1 then
        next
      else
        carrier = Carrier.where(type_cd: f.carrier_type_cd).first
        @carriers.store(carrier.description, f.ok_recs)
      end
    end
  rescue ActiveRecord::StatementInvalid
    @message = "DB Error" #kimishima
  end

  #JOBA001
  def jobcommand
    command = params[:command].to_i
    job_id = params[:main_id]
    @job = Job.find(job_id)
		#月次ジョブの場合、他のジョブが実行中でないかチェックする
		running_jobs = Job.where(type_cd: 0).where.not(job_id: @job.job_id, status: 3..4).where.not(status: 0).count
		logger.debug("jobs count: #{running_jobs} type_cd: #{@job.type_cd}")
		if command == 1 && @job.type_cd == '月次ジョブ' && running_jobs > 0
			logger.debug("can not start running")
			command = 0
		else
    	#ope_requestへinsert
    	if command == 6
				if @job.status == 0
					command = 11
				elsif @job.status == 2
					command = 12
				elsif @job.status == 3
					command = 13
				elsif @job.status == 4
					command = 14
				end
			end
    	request = OpeRequest.new(staff_id: session[:staff_id], ope_type_cd: command, ope_job_id: job_id)
    	request.save
		end
		logger.debug("\n\ncommand: #{command}\n")
    #3=完了と4=確定はボタンなし
    case command
    when 1 then
      @command = '実行'
    when 2 then
      @command = '中断'
    when 5 then
      @command = '再調査準備'
    when 6 then
      @command = '削除'
    when 7 then
      @command = '再開'
		when 11 then
			@command = '削除'
		when 12 then
			@command = '削除'
		when 13 then
			@command = '削除'
		when 14 then
			@command = '削除'
		when 0 then
			@command = '0'
    else
    end
  end

end

app/views/main/history.html.erb
<header>電話番号調査システム</header><!-- END "" -->
<main>
	<div id="content_conf">
	<table id="table_history">
	<tr>
		<th class="menu_active">17年3月</th>
		<th>4月</th>
		<th>5月</th>
		<th>6月</th>
		<th>7月</th>
		<th>8月</th>
		<th>9月</th>
		<th>10月</th>
		<th>11月</th>
		<th>12月</th>
		<th>1月</th>
		<th>2月</th>
	</tr>	
	</table>
	<p>受託ジョブの履歴</p>
		<table>
			<thead>
			<tr>
			  <th>ジョブ名</th>
			  <th>登録者</th>
			  <th>登録日時</th>
			  <th>開始日時</th>
			  <th>完了日時</th>
			  <th>対象件数</th>
			  <th>調査済み件数</th>
			  <th>自粛<br>リスト</th>
			  <th>回線<br>エラー</th>
			  <th>状態</th>
			</tr>
			</thead>
			<tbody>
			  <% @jobarchive_acces.each do |f| %>
			  <tr>
			    <td><%= f.description %></td>
			    <td><%= f.staff_nm %></td>
			    <td><%= f.created_at %></td>
			    <td><%= f.started_at %></td>
			    <td><%= f.finished_at %></td>
			    <td><%= f.all_recs %></td>
			    <td><%= f.ok_recs %></td>
			    <td><%= f.blk_recs %></td>
			    <td><%= f.err_recs %></td>
			    <td><%= f.status %></td>
			  </tr>
			  <% end %>
			</tbody>
		</table>
		<p>月次ジョブの履歴</p>
		<table>
			<thead>
			<tr>
			  <th>ジョブ名</th>
			  <th>登録者</th>
			  <th>登録日時</th>
			  <th>開始日時</th>
			  <th>完了日時</th>
			  <th>対象件数</th>
			  <th>調査済み件数</th>
			  <th>自粛<br>リスト</th>
			  <th>回線<br>エラー</th>
			  <th>状態</th>
			</tr>
			</thead>
			<tbody>
			  <% @jobarchive_month.each do |f| %>
			  <tr>
			    <td><%= f.description %></td>
			    <td><%= f.staff_nm %></td>
			    <td><%= f.created_at %></td>
			    <td><%= f.started_at %></td>
			    <td><%= f.finished_at %></td>
			    <td><%= f.all_recs %></td>
			    <td><%= f.ok_recs %></td>
			    <td><%= f.blk_recs %></td>
			    <td><%= f.err_recs %></td>
			    <td><%= f.status %></td>
			  </tr>
			  <% end %>
			</tbody>
		</table>
			<br>
		<table class="table_size_400">
			<thead>
				<tr>
					<th>キャリア種別</th>
					<th>調査済み件数</th>
				</tr>
			</thead>
			<tbody>
				<% @jobarchive.each do |f| %>
				<tr>
					<td><%= f.task_summary_archive.carrier_type_desc %></td>
					<td><%= f.task_summary_archive.ok_recs %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
	<button class="button_footer_conf"><%= link_to 'ジョブ管理トップ画面へ', main_index_path %></button>
</main><!-- END "" -->

app/views/main/index.html.erb
<header class="px-2 h1 bg-primary text-white">&nbsp;&nbsp;電話番号調査システム</header><!-- END "" -->
<div class="center-block">
<div class="col-md-10 col-md-offset-1">
<main>
  <div class="float-right">
  <%= link_to 'トップ画面へ', top_path, class:'btn btn-outline-primary btn-sm' %>
  <%= link_to 'ジョブ履歴へ', history_path, class:'btn btn-outline-primary btn-sm' %> 
  </div>
  <br>
 <p class="notice"><%= flash[:notice] %></p>
  <span class="topic h3 bg-faded border border-secondary rounded">&nbsp;受託ジョブ登録&nbsp;</span>
	<div id="page_job" class="center-block">
	<div class="col-md-12">
	<br>
		<table class="table_job td_input_left table table_border">
			<thead>
				<tr>
					<th class="table-active">ジョブ名</th>
					<th class="table-active">登録件数</th>
					<th class="table-active">対象件数</th>
					<th class="table-active">優先度</th>
					<th class="table-active">状態</th>
					<th class="table-active">進捗(%)</th>
					<th class="table-active">回線エラー</th>
					<th class="table-active">自粛リスト</th>
					<th class="table-active" colspan="3"></th>
				</tr>
			</thead>
			<tbody>
				<% @job_acces.each.map do |f| %>
				<tr>
					<td><%= f.description %></td>
					<td><%= number_with_delimiter(f.upd_recs, :delimiter => ',')%>件</td>
					<td><%= number_with_delimiter(f.alltask_recs, :delimiter => ',')%>件</td>
					<td><%= f.priority %></td>
					<% if f.job_status.status_cd >= 11 %>
						<td>削除中</td>
					<% elsif f.job_status.status_cd == 3 and (@errors["#{f.job_id}"] == 0 or @errors["#{f.job_id}"].nil?) and (@navail_errors["#{f.job_id}"] == 0 or @navail_errors["#{f.job_id}"].nil? ) and (@navail_ok["#{f.job_id}"] == 0 or @navail_ok["#{f.job_id}"].nil?) %>
						<td>完了</td>

					<% elsif f.job_status.status_cd == 3 and (@errors["#{f.job_id}"] == 0 or @navail_errors["#{f.job_id}"] == 0  or @navail_ok["#{f.job_id}"] == 0) %>
						<td>要再調査</td>
					<% else %>
						<td><%= f.job_status.description %></td>
					<% end %>
					<td><%= @acces_progress_list["#{f.job_id}"]%>%</td>
          <td>
						<% if @errors["#{f.job_id}"].nil? %>
							0件
						<% else %>
							<%= number_with_delimiter(@errors["#{f.job_id}"], :delimiter => ',') %>件
						<% end %>
          </td>
					<td><%= number_with_delimiter(@acces_navail_list["#{f.job_id}"], :delimiter => ',')%>件</td>
					<td><%= link_to '詳細', {action: 'show',:id => f.job_id}, {class: 'btn btn-primary'} %></td>
				</tr>
				<% end %>

			</tbody>
		</table>
	<%= link_to '新規追加', jobm_new_path, class:'btn btn-primary' %>
	</div>
	<br>
  <span class="topic h3 bg-faded border border-secondary rounded">&nbsp;月次ジョブ一覧&nbsp;</span>
	<div id="page_job" class="center-block">
	<div class="col-md-12">
	<br>
		<table class="table_job td_input_left table table_border">
			<thead>
				<tr>
					<th class="table-active">ジョブ名</th>
					<th class="table-active">登録件数</th>
					<th class="table-active">対象件数</th>
					<th class="table-active">状態</th>
					<th class="table-active">進捗(%)</th>
					<th class="table-active">回線エラー</th>
					<th class="table-active">自粛リスト</th>
					<th class="table-active" colspan="3"></th>
				</tr>
			</thead>
			<tbody>
			<% @job_month.each do |f| %>
				<tr>
					<td><%= f.description %></td>
					<td><%= number_with_delimiter(f.upd_recs, :delimiter => ',')%>件</td>
					<td><%= number_with_delimiter(f.alltask_recs, :delimiter => ',')%>件</td>

                                        <% if f.job_status.status_cd >= 11 %>
                                                <td>削除中</td>
                                        <% elsif f.job_status.status_cd == 3 and (@errors["#{f.job_id}"] == 0 or @errors["#{f.job_id}"].nil?) and (@navail_errors["#{f.job_id}"] == 0 or @navail_errors["#{f.job_id}"].nil? ) and (@navail_ok["#{f.job_id}"] == 0 or @navail_ok["#{f.job_id}"].nil?) %>
                                                <td>完了</td>
					<% elsif f.job_status.status_cd == 3 and (@errors["#{f.job_id}"] == 0 or @navail_errors["#{f.job_id}"] == 0  or @navail_ok["#{f.job_id}"] == 0) %>
                                                <td>要再調査</td>
                                        <% else %>
                                                <td><%= f.job_status.description %></td>
                                        <% end %>

					<td><%= @month_progress_list["#{f.job_id}"]%>%</td>
          <td>
						<% if @errors["#{f.job_id}"].nil? %>
							0件
						<% else %>
							<%= number_with_delimiter(@errors["#{f.job_id}"], :delimiter => ',') %>件
						<% end %>
          </td>
					<td><%= number_with_delimiter(@month_navail_list["#{f.job_id}"], :delimiter => ',')%>件</td>
					<td><%= link_to '詳細', {action: 'show',:id => f.job_id}, {class: 'btn btn-primary'} %></td>
				</tr>
			<% end %>
			</tbody>
		</table>
	<%= link_to '新規追加', jobm1_new_path, class:'btn btn-primary' %>
	</div>
</main>
</div>
</div>
<script type="text/javascript">
  function autoreload() {
    if (document.URL.match(/\/main$/)) location.reload()
  }
  setTimeout("autoreload()",1000*60);
</script>
<!-- END "" -->

app/views/main/jobcommand.html.erb
<header class="px-2 h1 bg-primary text-white">&nbsp;&nbsp;電話番号調査システム</header><!-- END "" -->
<div class="center-block">
<div class="col-md-10 col-md-offset-1">
<main>
  <br>
	<% if @command == '0' %>
		<div id="errorMsg" style="color: #f00;clear:both;">
			<h4>完了していない月次ジョブがあるため実行できませんでした。</h4>
		</div>
	<% else %>
	  <h4><%= @job.type_cd %>: <%= @job.description %>　<%= @command%>　受付しました。</h4>
	<% end %>
  <br><br><br><br><br><br><br><br>
<div class="float-right">
  <%= link_to 'ジョブ管理トップ画面へ', main_index_path, class:"btn btn-primary" %>
  <% unless @command == "削除" %>
  <%= link_to 'ジョブ詳細画面へ', {action: :show, :id => @job.job_id}, {class:"btn btn-primary"} %>
  <% end %>
</div>
</main><!-- END "" -->
</div>
</div>

app/views/main/show.html.erb
<header class="px-2 h1 bg-primary text-white">&nbsp;&nbsp;電話番号調査システム</header><!-- END "" -->
<div class="center-block">
<div class="col-md-10 col-md-offset-1">
<main>
  <br>
        <% errors_show = 0 %>
	<% @job.task_summaries.each do |f| %>
		<% next if f.carrier_type_cd == -1 %>
		<% errors_show += f.err_recs %>  
	<% end %>
	<% errors_show %>


	<% if @job.job_status.status_cd >= 11 %>
	    <span class="topic h3 bg-faded border border-secondary rounded">&nbsp;ジョブ詳細　状態：削除中&nbsp;</span>
	<% elsif @job.job_status.status_cd == 3 and (errors_show == 0 or errors_show.nil?) and (@navail == nil or @navail.err_recs == 0) and (@navail == nil or @navail.ok_recs == 0) %>
	    <span class="topic h3 bg-faded border border-secondary rounded">&nbsp;ジョブ詳細　状態：完了&nbsp;</span>
	<% elsif @job.job_status.status_cd == 3 and (errors_show == 0 or @navail.err_recs == 0  or @navail.ok_recs == 0) %>
	    <span class="topic h3 bg-faded border border-secondary rounded">&nbsp;ジョブ詳細　状態：要再調査&nbsp;</span>
	<% else %>
	    <span class="topic h3 bg-faded border border-secondary rounded">&nbsp;ジョブ詳細　状態：<%= @job.job_status.description%>&nbsp;</span>
	<% end %>

  <br>
  <br>
	<div id="page_job" class="center-block">
<div class="col-md-12">
		<table class="table_job td_input_left table table_border">
	    <tr>
	      <th class="table-active" >ジョブ種類</th>
	      <td><%= @job.type_cd %></td>
	    </tr>
	    <tr>
	      <th class="table-active" >ジョブ名</th>
	      <td><%= @job.description %></td>
	    </tr>
	    <tr>
	      <th class="table-active" >登録者名</th>
	      <td><%= @job.staff_nm %></td>
	    </tr>
	    <tr>
	      <th class="table-active" >ファイル名</th>
		<td>
		  <% unless @file == nil %>
	      	    <%= @file.filename %>
		  <% end %>&nbsp;
		</td>
	    </tr>
	    <tr>
	      <th class="table-active" >登録件数</th>
	      <td><%= number_with_delimiter(@job.upd_recs, :delimiter => ',')%>件</td>
	    </tr>
	    <tr>
	      <th class="table-active" >対象件数</th>
	      <td>
					<%= number_with_delimiter(@job.alltask_recs, :delimiter => ',')%>件 
					(残り <%= number_with_delimiter(@left, :delimiter => ',')%>件  進捗率:<%=@progress%>%)
				</td>
	    </tr>
	    <tr>
	      <th class="table-active" >例外件数</th>
	      <td>
					<% errors = 0 %>
					<% @job.task_summaries.each do |f| %>
						<% next if f.carrier_type_cd == -1 %>
						<% errors += f.err_recs %>  
					<% end %>
					回線エラー <%= number_with_delimiter(errors, :delimiter => ',') %>件  
					自粛リスト <% if @navail != nil %><%= number_with_delimiter(@navail.ok_recs, :delimiter => ',')%><% else %>0<% end %>件
				</td>
	    </tr>
	    </table>
	    </div><div class="col-md-12">
	    <table class="table_job table table_border">
	    	<thead>
	    		<th class="table-active" >調査開始時間</th>
	    		<th class="table-active" >経過時間</th>
					<% if @job.job_status.status_cd == 3 || @job.job_status.status_cd == 4 %>
						<th class="table-active" >完了日時</th>
					<% else %>
		    		<th class="table-active" >完了予定日時</th>
					<% end %>
	    	</thead>
	    	<tbody>
	    		<td>&nbsp;<%= @startdatetime %>&nbsp;</td>
	    		<td>&nbsp;<%= @elapsed %>&nbsp;</td>
	    		<td>&nbsp;<%= @estimated %>&nbsp;</td>
	    	</tbody>
	    </table>
	    </div><div class="col-md-9">
		<table class="table_size_400 table table_border">
			<thead>
				<tr>
					<th class="table-active" >キャリア種別</th>
					<th class="table-active" >調査済み件数</th>
				</tr>
			</thead>
			<tbody>
      <% if @carriers == nil or @carriers.length == 0 %>
        <tr>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
      <% else %>
        <% @carriers&.each{|key, value| %>
          <tr>
            <td><%= key %></td>
            <td><%=  number_with_delimiter(value, :delimiter => ',')%></td>
          </tr>
        <% } %>
      <% end %>
      </tbody>
		</table></div>
	</div>
  <div class="float-right">
    <% if @job.job_status.status_cd == 0%>
      <%= link_to '実行', main_jobcommand_path(main_id: @job.job_id, command: 1), class:'btn btn-primary' %>
      <%= link_to '削除', main_jobcommand_path(main_id: @job.job_id, command: 6), class:'btn btn-primary' %>
    <% elsif @job.job_status.status_cd == 1%>
      <%= link_to '中断', main_jobcommand_path(main_id: @job.job_id, command: 2), class:'btn btn-primary' %>
    <% elsif @job.job_status.status_cd == 2%>
      <%= link_to '結果取得', main_jobr_new_path(main_id: @job.job_id), class: 'btn btn-primary'%>
      <%= link_to '再開', main_jobcommand_path(main_id: @job.job_id, command: 7), class:'btn btn-primary' %>
      <%= link_to '削除', main_jobcommand_path(main_id: @job.job_id, command: 6), class:'btn btn-primary' %>

    <% elsif @job.job_status.status_cd == 3%>
      <%= link_to '結果取得', main_jobr_new_path(main_id: @job.job_id), class:'btn btn-primary' %>
      <%= link_to '削除', main_jobcommand_path(main_id: @job.job_id, command: 6), class:'btn btn-primary' %>
      <% if (errors_show != 0 or (@navail.nil? == false and @navail.err_recs.nil? == false and @navail.err_recs != 0)  or (@navail.nil? == false and @navail.ok_recs.nil? == false and @navail.ok_recs != 0)) %>
          <%= link_to '再調査準備', main_jobcommand_path(main_id: @job.job_id, command: 5), class:'btn btn-primary' %>
      <% end %>
    <% elsif @job.job_status.status_cd == 4%>
      <%= link_to '結果取得', main_jobr_new_path(main_id: @job.job_id), class:'btn btn-primary' %>
      <%= link_to '削除', main_jobcommand_path(main_id: @job.job_id, command: 6), class:'btn btn-primary' %>
    <% elsif @job.job_status.status_cd == 5%>
    <% elsif @job.job_status.status_cd == 6 || @job.job_status.status_cd >= 11 %>
    <% end %>
    <% if @job.type_cd == '月次ジョブ' %>
			<% if @job.job_status.status_cd != 6 && @job.job_status.status_cd != 4 && @job.job_status.status_cd < 11 %>
    		<%= link_to 'ファイル追加',  main_jobd_new_path(main_id: @job.job_id), class:'btn btn-primary' %>
			<% end %>
    <% end %>
    <%= link_to 'ジョブ管理トップ画面へ', main_index_path, class:'btn btn-primary' %>
  </div>
</main>
</div>
</div>
<!-- END "" -->