config/routes.rb
Rails.application.routes.draw do

  root to: redirect("/top")

  get 'history/new'

  #MENU001
  get 'top' => 'menu#menu001'

  scope '/main' do
    #JBOH001
    get 'history' => 'history#index'
    get 'history/:id' => 'history#show'
    #JBOM002 ~ JBOM005
    get 'jobm/new' => 'jobm#new'
    get 'jobm/show' => 'jobm#show'
    post 'jobm' => 'jobm#create'
    delete 'jobm/:id' => 'jobm#destroy'
    get 'jobm/:id/execute' => 'jobm#execute', as: 'jobm_execute'

    #JBOM101 ~ JBOM104
    get 'jobm1/new' => 'jobm1#new'
    get 'jobm1/show' => 'jobm1#show'
    post 'jobm1' => 'jobm1#create'
    post 'jobm1/confirm' => 'jobm1#confirm'
    get 'jobm1/finish' => 'jobm1#finish'
    delete 'jobm1/:id' => 'jobm1#destroy'
  end

  #JOBM001
  #JOBD001
  resources :main, only: [:index, :show] do
    #JOBA001
    get 'jobcommand', to: 'main#jobcommand'
    #JOBR001
    get 'jobr/new' => 'jobr#new'
    #JOBR002
    post 'jobr/confirm' => 'jobr#confirm'
    #JOBR003
    post 'jobr' => 'jobr#create'
    #JOBR004
    get 'jobr/show' => 'jobr#show'
    delete 'jobr/:id' => 'jobr#destroy'

    #JOBD101
    get 'jobd/new' => 'jobd#new'
    #JOBDD102
    post 'jobd/confirm' => 'jobd#confirm'
    #JOBD0103
    post 'jobd' => 'jobd#create'
    #JOBD104
    get 'jobd/finish' => 'jobd#finish'
    get 'jobd/show' => 'jobd#show'
    delete 'jobd/:id' => 'jobd#destroy'
  end

  #MENU002
  get 'menu/menu002'

  scope 'setting' do
    #CONF001
    get 'conf' => 'conf#index'
    #CONF002,CONF003
    get 'conf/:id' => 'conf#show'
    post 'conf/:id' => 'conf#update', as: 'conf_update'
    get 'conf/:id/done' => 'conf#done', as: 'conf_done'

    #CONF101
    get 'conf1' => 'conf1#index'
    get 'conf1/new' => 'conf1#new'
    post 'conf1/new' => 'conf1#create'
    get 'conf1/:id' => 'conf1#show'
    post 'conf1/:id' => 'conf1#update'
    post 'conf1' => 'conf1#update'
    delete 'conf1/:id' => 'conf1#destroy'

    #CONF201
    get 'conf2' => 'conf2#index'
    post 'conf2' => 'conf2#update'
    post 'conf2/search' => 'conf2#search'
    get 'conf2/search' => 'conf2#search'
    post 'conf2/new' => 'conf2#new'
    delete 'conf2' => 'conf2#destroy'
    get 'download' => 'conf2#download'

    #CONF202
    get 'viewlog' => 'conf2#history'
    get 'downloadlog' => 'conf2#downloadlog'
  end

end

app/controllers/jobm_controller.rb
class JobmController < ApplicationController
  before_action :set_job, only: [:show, :edit, :destroy]

  #jobm002
  def new
    @job = Job.new
  end

  #jobm004 not page view
  def create
    @job = Job.new(job_params.merge({
      job_id: ActiveRecord::Base.connection.select_value('SELECT gen_jobid()'), # ジョブID生成
      type_cd: Job.type_cds['受託ジョブ'], # 固定値 1
      staff_id: 'drbell', # ダイジェスト認証のユーザー名を取得
      status: 0, # 状態の初期値は待機（0）
      inner_pri: 0,
      created_at: Time.current
    }))

    file = params[:file_csv][0]
    filename = file.original_filename
    path = UPDATA + @job.job_id.to_s + "_" + filename
    telnum_file = @job.telnum_files.new(filename: filename, loaded: false, created_at: Time.current)

    open(file.tempfile.path){|f|
      while f.gets; end
      @line_count = f.lineno
      @job.upd_recs = @line_count
    }

    ActiveRecord::Base.transaction do
      @job.save!
      telnum_file.save!
    end
    FileUtils.mv(file.tempfile, path)
    FileUtils.chmod(0664, path)

    @notice = '以下の通り、設定と対象リストの登録が完了しました。'
    render :done
  rescue => e
    @notice = '登録に失敗しました。'
    render :new
  end

  def execute
    @job = Job.find(params[:id])

    @ope_requests = OpeRequest.new
    @ope_requests.staff_id = @job.staff_id # 登録者ID
    @ope_requests.ope_type_cd = 1 # 作業種別コード(実行)
    @ope_requests.ope_job_id = @job.job_id # 作業対象ジョブID

    unless @ope_requests.save
      flash[:notice] = '即時実行できませんでした。'
    end

    redirect_to main_index_path
  end

  def show
    @notice = params[:notice]
  end

  def destroy
    @job.destory
  end

  private
  def set_job
    @job = Job.find(params[:id])
  end

  def job_params
    p = params.require(:job).permit(:job_id, :description, :staff_nm, :priority)
    p['priority'] = p['priority'].to_i
    p
  end
end

app/views/jobm/confirm.html.erb
<header>電話番号調査システム</header>
<main>
  <p class="topic">受託ジョブ登録</p>
  <p class="border"></p>
  <div id="crumbs">
    <p>登録</p>
    <p class="menu_active_job">確認</p>
    <p>処理中</p>
    <p>完了</p>
  </div>
  <%= form_for @job, url: jobm_path do |f| %>
    <div id="page_job">
      <table>
        <tr>
          <th>ジョブ名</th>
          <td><%= f.hidden_field :description %><%= @job.description %></td>
        </tr>
        <tr>
          <th>登録者名</th>
          <td><%= f.hidden_field :staff_nm %><%= @job.staff_nm %></td>
        </tr>
        <tr>
          <th>優先度</th>
          <td><%= f.hidden_field :priority %><%= @job.priority %></td>
        </tr>
        <tr>
          <th>調査対象電話番号リスト</th>
          <td><%= hidden_field_tag :file_csv, @file_csv %><%= @file_csv.original_filename %></td>
        </tr>
      </table>
    </div>
    <%= f.submit '内容修正', name: 'back', class: 'content_conf_button' %>
    <%= f.submit '登録', class: 'content_conf_button' %>
  <% end %>
</main>

app/views/jobm/done.html.erb
<header class="px-2 h1 bg-primary text-white">&nbsp;&nbsp;電話番号調査システム</header><!-- END "" -->
<div class="center-block col-md-10 col-md-offset-1">
<main>
  <br>
  <span class="topic h3 bg-faded border border-secondary rounded">&nbsp;受託ジョ
ブ登録&nbsp;</span>
  <div id="page_job" class="center-block">
  <div class="col-md-12">
  <br>
  <table class="table_job td_input_left table table_border">
  <tr>
    <th class="table-active">登録</th>
    <th class="table-active">確認</th>
    <th class="table-active">処理中</th>
    <th class="table-info">完了</th>
  </tr>
  </table>
  <div id="page_job">
    <h4><%= @notice %></h4>
    <table class="td_input_left table table_border">
      <tr>
        <th class="h5 table-active table_size">ジョブ名</th>
        <td class="h5" colspan="3"><%= @job.description %></td>
      </tr>
      <tr>
        <th class="h5 table-active">登録者名</th>
        <td class="h5" colspan="3"><%= @job.staff_nm %></td>
      </tr>
      <tr>
        <th class="h5 table-active">優先度</th>
        <td class="h5" colspan="3"><%= @job.priority %></td>
      </tr>
      <tr>
        <th class="h5 table-active">調査対象電話番号リスト</th>
        <td class="h5"><%= @job.telnum_files.first.filename %></td>
        <th class="h5 table-active">登録件数</th>
        <td class="h5"><%= @line_count %></td>
      </tr>
    </table>
  </div>
 <div class="float-right">
  <%= link_to '即時実行', jobm_execute_path(@job), class:"btn btn-primary" %>
  <%= link_to 'ジョブ管理トップ画面へ', main_index_path, class:"btn btn-primary" %>
</div>
</main><!-- END "" -->
</div>
</div>

app/views/jobm/jobm004.html.erb
<header>電話番号調査システム</header><!-- END "" -->
<main>
  <p class="topic">受託ジョブ登録</p>
  <div>
    <p class="border"></p>
    <div id="crumbs">
      <p>登録</p>
      <p>確認</p>
      <p class="menu_active_job">処理中</p>
      <p>完了</p>
    </div>
  </div>
  <div id="page_job">
    <p>対象リスト登録中です<br>しばらくお待ちください。</p>
  </div>
</main><!-- END "" -->

app/views/jobm/new.html.erb
<header class="px-2 h1 bg-primary text-white">&nbsp;&nbsp;電話番号調査システム</header><!-- END "" -->
<div class="center-block col-md-10 col-md-offset-1">
<main>
  <br>
  <span class="topic h3 bg-faded border border-secondary rounded">&nbsp;受託ジョブ登録&nbsp;</span>
  <div id="page_job" class="center-block">
  <div class="col-md-12">
  <br>
  <table class="table_job td_input_left table table_border">
  <tr>
    <th class="table-info">登録</th>
    <th class="table-active">確認</th>
    <th class="table-active">処理中</th>
    <th class="table-active">完了</th>
  </tr>
  </table>
  <!-- This is just to clear float -->
  <div style="clear:both"></div>
  <p class="notice"><%= @notice %></p>
  <% if !@errors.nil? && @errors.any? %>
      <div id="error_explanation">
        <ul>
          <% @errors.each do |error| %>
            <li>
              <%= error %>
            </li>
          <% end %>
        </ul>
      </div>
 <% end %>

  <div id="errorMsg" style="color: #f00;clear:both;"></div>

  <%= form_for @job, url: { action: 'create' }, html: { multipart: true } do |f| %>
      <div id="page_job">
        <table class="td_input_left table table_border">
          <tr>
           <th class="h5 table-active table_size"><%= f.label 'ジョブ名' %></th>
           <td class="h5"><%= f.text_field :description, class: 'form-control', autofocus: true %></td>
         </tr>
          <tr>
            <th class="h5 table-active"><%= f.label '登録者名' %></th>
            <td class="h5"><%= f.text_field :staff_nm, class: 'form-control' %></td>
          </tr>
          <tr>
            <th class="h5 table-active"><%= f.label '優先度' %></th>
            <td class="h5"><%= f.select(:priority, Job.priorities.slice(:普通, :高, :急 ), html: { class:'form-control' })  %></td>
          </tr>
          <tr class="new_addfiles">
            <th class="h5 table-active"><%= f.label '調査対象電話番号リスト' %></th>
            <td class="h5"><%= file_field_tag :file_csv %></td>
          </tr>
        </table>
      </div>
  <% end %>
  <div id="new_button_group" class="float-right">
    <%= link_to '戻る', main_index_path, class: 'btn btn-primary' %>
    <a id="confirm-button" class="content_conf_button data-mode-button btn btn-primary text-white">確認</a>
  </div>
  <div id="confirm_button_group" class="float-right" style="display: none;">
    <a class="content_conf_button data-mode-button btn btn-primary text-white" data-mode="new">内容修正</a>
    <a class="content_conf_button data-mode-button btn btn-primary text-white" data-mode="regist">登録</a>
  </div>
  <div id="regist_display" style="display: none;">
    <h3 class="text-center">対象リスト登録中です。<br>しばらくお待ちください。</h3>
  </div>
</main><!-- END "" -->
</div>