config/routes.rb
Rails.application.routes.draw do

  root to: redirect("/top")

  get 'history/new'

  #MENU001
  get 'top' => 'menu#menu001'

  scope '/main' do
    #JBOH001
    get 'history' => 'history#index'
    get 'history/:id' => 'history#show'
    #JBOM002 ~ JBOM005
    get 'jobm/new' => 'jobm#new'
    get 'jobm/show' => 'jobm#show'
    post 'jobm' => 'jobm#create'
    delete 'jobm/:id' => 'jobm#destroy'
    get 'jobm/:id/execute' => 'jobm#execute', as: 'jobm_execute'

    #JBOM101 ~ JBOM104
    get 'jobm1/new' => 'jobm1#new'
    get 'jobm1/show' => 'jobm1#show'
    post 'jobm1' => 'jobm1#create'
    post 'jobm1/confirm' => 'jobm1#confirm'
    get 'jobm1/finish' => 'jobm1#finish'
    delete 'jobm1/:id' => 'jobm1#destroy'
  end

  #JOBM001
  #JOBD001
  resources :main, only: [:index, :show] do
    #JOBA001
    get 'jobcommand', to: 'main#jobcommand'
    #JOBR001
    get 'jobr/new' => 'jobr#new'
    #JOBR002
    post 'jobr/confirm' => 'jobr#confirm'
    #JOBR003
    post 'jobr' => 'jobr#create'
    #JOBR004
    get 'jobr/show' => 'jobr#show'
    delete 'jobr/:id' => 'jobr#destroy'

    #JOBD101
    get 'jobd/new' => 'jobd#new'
    #JOBDD102
    post 'jobd/confirm' => 'jobd#confirm'
    #JOBD0103
    post 'jobd' => 'jobd#create'
    #JOBD104
    get 'jobd/finish' => 'jobd#finish'
    get 'jobd/show' => 'jobd#show'
    delete 'jobd/:id' => 'jobd#destroy'
  end

  #MENU002
  get 'menu/menu002'

  scope 'setting' do
    #CONF001
    get 'conf' => 'conf#index'
    #CONF002,CONF003
    get 'conf/:id' => 'conf#show'
    post 'conf/:id' => 'conf#update', as: 'conf_update'
    get 'conf/:id/done' => 'conf#done', as: 'conf_done'

    #CONF101
    get 'conf1' => 'conf1#index'
    get 'conf1/new' => 'conf1#new'
    post 'conf1/new' => 'conf1#create'
    get 'conf1/:id' => 'conf1#show'
    post 'conf1/:id' => 'conf1#update'
    post 'conf1' => 'conf1#update'
    delete 'conf1/:id' => 'conf1#destroy'

    #CONF201
    get 'conf2' => 'conf2#index'
    post 'conf2' => 'conf2#update'
    post 'conf2/search' => 'conf2#search'
    get 'conf2/search' => 'conf2#search'
    post 'conf2/new' => 'conf2#new'
    delete 'conf2' => 'conf2#destroy'
    get 'download' => 'conf2#download'

    #CONF202
    get 'viewlog' => 'conf2#history'
    get 'downloadlog' => 'conf2#downloadlog'
  end

end

app/controllers/jobd_controller.rb
class JobdController < ApplicationController
  #before_action :set_, only: [:show, :edit, :update, :destroy]
	before_action :set_job_month, only: [:show, :edit, :update, :destroy]

  #JOBD101
  def new
		@job = Job.find(params[:main_id])
		if @job.type_cd == '受託ジョブ'
			redirect_to "/main/#{@job.job_id}" and return
		end
		@errors_msg = params[:alert]
  end

  #JOBD102
  def confirm
		uploaded_files = []
		total_file = 0
		TelnumFile.transaction do
			@job = Job.find(params[:main_id])

			total_line = @job.upd_recs
			line_count = 0
			file_params[:file_csv].each do |file|
				#ファイルのアップロード
				new_filepath = File.join(UPDATA, @job.job_id.to_s + "_" + file.original_filename)
				uploaded_files.push(new_filepath)
				File.open(new_filepath, "wb") {|f|
					File.open(file.tempfile) {|rf|
						rf.each_line do |line|
							f.write(line)
						end
						line_count = rf.lineno
						rf.close
					}
					f.close
				}
				total_line += line_count

				#電話番号データファイルの登録
				@telnum_files = TelnumFile.new
				@telnum_files.job_id = @job.job_id
				@telnum_files.filename = file.original_filename
				@telnum_files.loaded = false
				if !@telnum_files.valid?
					redirect_to :action => "new", :main_id => @job.job_id, :alert => @telnum_files.errors.full_messages and return
				end
				@telnum_files.save!
				total_file += 1
				 if @job.status == 3
					@job.status = 2
				 end
				
				#アップロード件数を追加
				@job.upd_recs = total_line
				@job.save!
			end
		end
		redirect_to :action => "finish", :main_id => @job.job_id, :file_count => total_file
		rescue => e
		render plaint: e.message
		uploaded_files.each do |filename|
			if File.exist?(filename)
				File.unlink(filename)
			end
		end
  end

	def finish
		@job = Job.find(params[:main_id])
		@files = []
		@telnumfile = TelnumFile.where(job_id: @job.job_id).order("created_at DESC").limit(params[:file_count])
		@telnumfile.each do |file|
			filepath = File::join(UPDATA, @job.job_id.to_s + "_" + file[:filename])
			open(filepath){|f|
				while f.gets; end
				@line_count = f.lineno
			}
			@files.push({:filename => file[:filename], :line_count => @line_count})
		end
	end

  #JOBD103 not page view
  def create
  end

  #JOBD104
  def show
  end

  def destroy
  end

  private
  def set_
    #@ = .find(params[:id])
  end

  def file_params
    params.permit({file_csv: []})
  end
end

app/views/jobd/confirm.html.erb
<header>電話番号調査システム</header><!-- END "" -->
<main>
  <p class="topic">月次ジョブ登録</p>
  <p class="border"></p>
      <div id="crumbs">
        <p>登録</p>
        <p class="menu_active_job">確認</p>
        <p>処理中</p>
        <p>完了</p>
      </div>
	<div id="page_job">
		<table>
	    <tr>
	      <th>ジョブ名</th>
	      <td> f.hidden_field :description </td>
	    </tr>
	    <tr>
	      <th>調査対象電話番号リスト</th>
	      <td> :file_csv </td>
	    </tr>
		</table>
	</div>
		<button class="content_conf_button">f.submit '確認', class: 'content_conf_button'</button>
		<button class="content_conf_button"> f.submit '内容修正', name: 'back', class: 'content_conf_button'</button>

</main><!-- END "" -->

app/views/jobd/finish.html.erb
<header class="px-2 h1 bg-primary text-white">&nbsp;&nbsp;電話番号調査システム</header><!-- END "" -->
<div class="center-block">
<div class="col-md-10 col-md-offset-1">
<main>
  <br>
  <span class="topic h3 bg-faded border border-secondary rounded">&nbsp;ジョブファイル追加&nbsp;</span>
<div id="page_job" class="center-block">
<div class="col-md-12">
<br>
<table class="table_job td_input_left table table_border">
  <tr>
    <th class="table-active">登録</th>
    <th class="table-active">確認</th>
    <th class="table-active">処理中</th>
    <th class="table-info">完了</th>
  </tr>
</table>
	<div style="clear:both;">
      <h2>以下の通り、設定と対象リストの登録が完了しました。</h2>
    </div>
    <div id="page_job">
      <table class="table_job td_input_left table table_border">
        <tr>
          <th class="h5 table-active table_size">ジョブ名</th>
          <td class="h5" colspan="3"><%= @job.description %></td>
        </tr>
        <% @files.each do |f| %>
        <tr>
          <th class="h5 table-active table_size">調査対象電話番号リスト</th>
          <td class="h5"><%= f[:filename] %></td>
          <th class="h5 table-active">登録件数</th>
          <td class="h5"><%= f[:line_count] %></td>
        </tr>
        <% end %>
      </table>
	<div class="float-right">
		<%= link_to 'ジョブ詳細画面へ', {controller: "main", action: "show", :id => @job.job_id}, class: "btn btn-primary" %>
    		<%= link_to 'ジョブ管理トップ画面へ', main_index_path, class: "btn btn-primary" %>
</main><!-- END "" -->
</div>
</div>

app/views/jobd/jobd103.html.erb
<header>電話番号調査システム</header><!-- END "" -->
<main>
  <p class="topic">ジョブファイル追加</p>
  <div>
  <p class="border"></p>
      <div id="crumbs">
        <p>登録</p>
        <p>確認</p>
        <p class="menu_active_job">処理中</p>
        <p>完了</p>
  	  </div>
  </div>
	<div id="page_job">
		<p>対象リスト登録中です<br>しばらくお待ちください。</p>
	</div>
</main><!-- END "" -->

app/views/jobd/new.html.erb
<header class="px-2 h1 bg-primary text-white">&nbsp;&nbsp;電話番号調査システム</header><!-- END "" -->
<div class="center-block">
<div class="col-md-10 col-md-offset-1">
<main>
  <br>
  <span class="topic h3 bg-faded border border-secondary rounded">&nbsp;ジョブファイル追加&nbsp;</span>
        <div id="page_job" class="center-block">
        <div class="col-md-12">
        <br>
  <table class="table_job td_input_left table table_border">
  <tr>
    <th class="table-info">登録</th>
    <th class="table-active">確認</th>
    <th class="table-active">処理中</th>
    <th class="table-active">完了</th>
  </tr>
  </table>

	<div id="errorMsg" style="color: #f00;clear:both;">
		<% if !@message.present? %>
			<%= @errors_msg %><br>
		<% end %>
	</div>

	<%= form_tag({action: :confirm}, multipart: true) do %>
		<div id="page_job">
		<table class="table_job td_input_left table table_border">
				<tr>
	    	  <th class="h5 table-active table_size"><%= label_tag 'ジョブ名'%></th>
	    	  <td class="h5"><%= @job.description %></td>
	    	</tr>
				<tr class="new_addfiles">
	      	<th class="h5 table-active"><%= label_tag '調査対象電話番号リスト' %></th>
	      	<td class="h5"><%= file_field_tag :file_csv, class: "addfile" %> <%= button_tag type:"button", class: "btn btn-primary jobm1_new_delfile_btn", style: "display: none" do %>削除<% end %></td>
	    	</tr>
			</table>
			<%= button_tag type: "button", class: "btn btn-primary button_addfile_job", id: "jobm1_new_addfile_btn" do %>
				<%= 'ファイル追加' %>
			<% end %>
		</div>
	<% end %>
	<div class="float-right" id="new_button_group">
		<%= link_to '戻る', main_path(@job.job_id), class:"btn btn-primary" %>
		<button id="confirm-button" class="btn btn-primary data-mode-button">確認</button>
	</div>
	<div id="confirm_button_group" style="display: none;" class="float-right">
		<button class="btn btn-primary data-mode-button" data-mode="new">内容修正</button>
		<button class="btn btn-primary data-mode-button" data-mode="regist">登録</button>
	</div>
	<div id="regist_display" style="display: none;">
		<h3 class="text-center">対象リスト登録中です。<br>しばらくお待ちください。<h3>
	</div>
</main><!-- END "" -->
</div>
</div>

app/views/jobd/show.html.erb
<header>電話番号調査システム</header><!-- END "" -->
<main>
  <p class="topic">月次ジョブ登録</p>
  <p class="border"></p>
      <div id="crumbs">
        <p>登録</p>
        <p class="menu_active_job">確認</p>
        <p>処理中</p>
        <p>完了</p>
      </div>
	<div id="page_job">
		<table>
	    <tr>
	      <th>ジョブ名</th>
	      <td> f.hidden_field :description </td>
	    </tr>
	    <tr>
	      <th>調査対象電話番号リスト</th>
	      <td> :file_csv </td>
	    </tr>
	    <tr>
	      <th>調査対象電話番号リスト</th>
	      <td>xxx会社_201704.csv</td>
	      <th class="table_size"> 登録件数</th>
	      <td>20,000</td>
	    </tr>
		</table>
	</div>
		<button class="content_conf_button">f.submit '確認', class: 'content_conf_button'</button>
		<button class="content_conf_button"> link_to '内容修正', name: :new, class: 'content_conf_button'</button>

</main><!-- END "" -->